adding return card to log
HL7-DaVinci/CRD pull request #241
Opened 2021-06-16 20:08 UTC by lpqdao

2021-06-17 16:34 UTC, KeeyanGhoreshi requested changes

2021-06-17 16:34 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/components/requestLog/DetailEntry.js
> +                 { this.unfurlJson(JSON.parse(atob(this.props.data.requestCard)))}
`atob()` converts base64 to strings, the cards should already be a string so it's unnecessary here.

2021-06-17 16:34 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/components/requestLog/DetailEntry.js
> +            showCard: false
should be `showCards`, since it's an array.  That goes for all instances of `card` here as well, should be plural.

2021-06-17 16:34 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/components/requestLog/DetailEntry.js
> +                 <div className = "requestCard">
the className should be `requestBody`, so that it gets the correct styling.  Should also  rename the class to something like `jsonDisplay` since the class is no longer specific to the request body.

2021-06-17 16:34 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/components/requestLog/DetailEntry.js
> +                 { this.unfurlJson(JSON.parse(atob(this.props.data.requestCard)))}
`this.props.data.requestCard` should be `this.props.data.cardList`, since the incoming object from the database will have the cardlist stored under the name given to it in `RequestLog.java`.

2021-06-17 19:47 UTC, plarocque4 commented on server/src/main/java/org/hl7/davinci/endpoint/controllers/DataController.java
> +    logger.info("HELLO 2");
This should be reverted to a more meaningful log?

2021-06-18 19:24 UTC, KeeyanGhoreshi requested changes
It seems like the entire `package-lock.json` file was accidentally deleted from the repository.  Should add that back in.

2021-06-18 19:24 UTC, KeeyanGhoreshi commented on server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
> +    requestService.edit(requestLog);
`handleRequest()` also returns after erroring (line 158), you should add the cards in that case as well.

2021-06-18 19:24 UTC, KeeyanGhoreshi commented on server/src/main/java/org/hl7/davinci/endpoint/database/RequestLog.java
> +    // setCardList(cardList);
I think this comment can be removed

2021-06-18 19:24 UTC, KeeyanGhoreshi commented on server/src/main/java/org/hl7/davinci/endpoint/database/RequestLog.java
> +    //this.cardCounter = 0;
this comment as well

2021-06-18 19:24 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/components/requestLog/DetailEntry.js
> +                 { this.unfurlJson(JSON.parse((this.props.data.cardList))) }
you got an extra pair of parentheses here

2021-06-18 19:24 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/containers/RequestLog.js
> +        const requestData = await fetch("http://localhost:8090/" + 'api/requests', {
this should be reverted to baseUrl

2021-06-18 19:24 UTC, KeeyanGhoreshi commented on server/src/main/resources/node_interfaces/src/containers/RequestLog.js
> +        //console.log(requestData)
delete this extra comment

2021-06-18 21:06 UTC, KeeyanGhoreshi commented on server/src/main/java/org/hl7/davinci/endpoint/database/RequestLog.java
> +  public void setAddCardList(Object card) {
`setAddCardList` doesn't sound quite right.  This function should probably be named something like `setCardListFromCards` or  `setFromCards`.  Could also rename `card` to `cards` to be more descriptive.

2021-07-19 18:58 UTC, KeeyanGhoreshi approved these changes

2021-08-04 21:08 UTC, KeeyanGhoreshi commented on server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
> -      if (results.getDrugInteraction().getApplies()) {
is this supposed to be deleted?

2021-08-05 19:52 UTC, plarocque4 requested changes
I just tested this out, when I clicked on the Show Cards button, there were no cards displayed. Please retest and let me know if you see the problem.

2021-08-06 03:00 UTC, plarocque4 commented on server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
> +    CardBuilder.errorCardIfNonePresent(response);
I think this needs to be moved back into the if (errorCardOnEmpty)

2021-08-06 19:21 UTC, plarocque4 commented on server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
>        CardBuilder.errorCardIfNonePresent(response);
Could you just move this up to within the other "if (errorCardOnEmpty)" check above?

2021-08-06 19:50 UTC, plarocque4 commented on server/src/main/java/org/hl7/davinci/endpoint/cdshooks/services/crd/CdsService.java
> +      CardBuilder.errorCardIfNonePresent(response);
I hate to ask you to move this again, but it needs to be where it was after the !foundApplicableRule check. That will add a card for no rules found, and this errorCardIfNonePresent will add an error if there were none, so the other "no rules" card should come first.

2021-08-06 20:04 UTC, plarocque4 approved these changes
Looks good

2021-08-06 20:04 UTC, merged